name: mybiuld
on:
  pull_request:
    branches: [main]
    
jobs:
  dummy_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        
      - name: pass
        run: echo 'Make renovate automerge executed..'
